import jsPDF from "jspdf"

export const downloadRoadmapPDF = (courses, completedCourses) => {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()

  // ── Header ──────────────────────────────────
  doc.setFillColor(11, 15, 26)
  doc.rect(0, 0, pageWidth, 40, "F")

  doc.setTextColor(96, 165, 250)
  doc.setFontSize(22)
  doc.setFont("helvetica", "bold")
  doc.text("SkillPath AI", 20, 18)

  doc.setTextColor(136, 146, 164)
  doc.setFontSize(10)
  doc.setFont("helvetica", "normal")
  doc.text("Personalized Learning Roadmap", 20, 28)
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, 20, 35)

  // ── Role info ────────────────────────────────
  doc.setFillColor(20, 28, 46)
  doc.rect(0, 44, pageWidth, 24, "F")

  doc.setTextColor(232, 237, 245)
  doc.setFontSize(12)
  doc.setFont("helvetica", "bold")
  doc.text("Target Role: Data Analyst", 20, 54)

  doc.setTextColor(136, 146, 164)
  doc.setFontSize(10)
  doc.setFont("helvetica", "normal")
  doc.text(
    `Progress: ${completedCourses.length} of ${courses.length} courses complete`,
    20, 63
  )

  // ── Match scores ─────────────────────────────
  let y = 82

  doc.setFillColor(26, 15, 16)
  doc.roundedRect(15, y - 6, 80, 26, 3, 3, "F")
  doc.setTextColor(255, 77, 106)
  doc.setFontSize(9)
  doc.setFont("helvetica", "bold")
  doc.text("CURRENT MATCH", 55, y + 2, { align: "center" })
  doc.setFontSize(18)
  doc.text("43%", 55, y + 14, { align: "center" })

  doc.setFillColor(10, 22, 40)
  doc.roundedRect(110, y - 6, 80, 26, 3, 3, "F")
  doc.setTextColor(0, 229, 160)
  doc.setFontSize(9)
  doc.setFont("helvetica", "bold")
  doc.text("AFTER ROADMAP", 150, y + 2, { align: "center" })
  doc.setFontSize(18)
  doc.text("91%", 150, y + 14, { align: "center" })

  // ── Section title ────────────────────────────
  y = 122
  doc.setTextColor(96, 165, 250)
  doc.setFontSize(9)
  doc.setFont("helvetica", "bold")
  doc.text("YOUR LEARNING PATHWAY", 20, y)

  doc.setDrawColor(96, 165, 250)
  doc.setLineWidth(0.3)
  doc.line(20, y + 3, pageWidth - 20, y + 3)

  y = 134

  // ── Course cards ─────────────────────────────
  courses.forEach((course, index) => {
    const isCompleted = completedCourses.includes(course.id)

    // Card background
    if (isCompleted) {
      doc.setFillColor(10, 26, 20)
    } else {
      doc.setFillColor(20, 28, 46)
    }
    doc.roundedRect(15, y, pageWidth - 30, 30, 3, 3, "F")

    // Left accent bar
    if (isCompleted) {
      doc.setFillColor(0, 229, 160)
    } else if (course.priority === "HIGH PRIORITY") {
      doc.setFillColor(255, 77, 106)
    } else {
      doc.setFillColor(255, 149, 0)
    }
    doc.rect(15, y, 3, 30, "F")

    // Step number circle
    doc.setFillColor(59, 130, 246)
    doc.circle(28, y + 15, 6, "F")
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(8)
    doc.setFont("helvetica", "bold")
    doc.text(
      String(index + 1).padStart(2, "0"),
      28, y + 17,
      { align: "center" }
    )

    // Course title
    doc.setTextColor(isCompleted ? 136 : 232, isCompleted ? 146 : 237, isCompleted ? 164 : 245)
    doc.setFontSize(11)
    doc.setFont("helvetica", "bold")
    doc.text(course.title, 40, y + 11)

    // Subtitle
    doc.setTextColor(136, 146, 164)
    doc.setFontSize(9)
    doc.setFont("helvetica", "normal")
    doc.text(course.subtitle, 40, y + 19)

    // Tags
    doc.setFontSize(8)
    doc.text(`${course.duration}  •  ${course.skill}`, 40, y + 26)

    // Priority badge
    if (course.priority === "HIGH PRIORITY") {
      doc.setTextColor(255, 77, 106)
    } else {
      doc.setTextColor(255, 149, 0)
    }
    doc.setFont("helvetica", "bold")
    doc.text(course.priority, pageWidth - 20, y + 11, { align: "right" })

    // Completed checkmark
    if (isCompleted) {
      doc.setTextColor(0, 229, 160)
      doc.setFontSize(10)
      doc.text("✓ Completed", pageWidth - 20, y + 22, { align: "right" })
    }

    y += 35

    // Page break if needed
    if (y > 260 && index < courses.length - 1) {
      doc.addPage()
      y = 20
    }
  })

  // ── Footer ───────────────────────────────────
  const totalPages = doc.internal.getNumberOfPages()
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i)
    doc.setFillColor(11, 15, 26)
    doc.rect(0, 282, pageWidth, 15, "F")
    doc.setTextColor(136, 146, 164)
    doc.setFontSize(8)
    doc.setFont("helvetica", "normal")
    doc.text(
      "Generated by SkillPath AI • Skip what you know. Learn what you need.",
      pageWidth / 2, 290,
      { align: "center" }
    )
    doc.text(`Page ${i} of ${totalPages}`, pageWidth - 20, 290, { align: "right" })
  }

  doc.save("SkillPath-AI-Roadmap.pdf")
}